- name: MySQL | Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: MySQL | Ensure mysql is installed
  apt: pkg={{ item }} state=present
  with_items:
      - mysql-client
      - mysql-server
      - python-mysqldb

- name: MySQL | Start the MySQL service
  action: service name=mysql state=started
      
# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: MySQL | Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: MySQL | Copy .my.cnf file with root password credentials
  template: src=../templates/.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: MySQL | Remove the MySQL test database
  action: mysql_db db=test state=absent
