# Only run "update_cache=yes" if the last one is more than more than 3600 seconds ago
- name: Common | update cache
  apt: update_cache=yes cache_valid_time=3600

- name: Common | Install utils
  apt: pkg={{ item }} state=installed
  with_items:
    - git
    - sendmail
    - unzip
    - wget
